-- Minimal schema (MVP)
create table if not exists titles (
    id bigint generated by default as identity primary key,
    tmdb_id int,
    type text check (type in ('movie', 'series')) not null,
    title text not null,
    slug text unique not null,
    release_date date,
    chronology_index numeric,
    phase text,
    saga text,
    poster_url text,
    backdrop_url text,
    overview text,
    is_canon_mcu boolean default true
);
create table if not exists profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    username text unique,
    avatar_url text,
    favorite_hero text,
    created_at timestamptz default now()
);
create table if not exists progress (
    user_id uuid not null references profiles(id) on delete cascade,
    title_id bigint not null references titles(id) on delete cascade,
    status text check (
        status in ('queued', 'watching', 'watched', 'skipped')
    ) not null default 'queued',
    watched_at timestamptz,
    primary key (user_id, title_id)
);
-- RLS
alter table titles enable row level security;
create policy "titles public read" on titles for
select using (true);
alter table profiles enable row level security;
create policy "profiles read own" on profiles for
select using (auth.uid() = id);
create policy "profiles write own" on profiles for
insert with check (auth.uid() = id);
create policy "profiles update own" on profiles for
update using (auth.uid() = id);
alter table progress enable row level security;
create policy "progress read own" on progress for
select using (auth.uid() = user_id);
create policy "progress write own" on progress for
insert with check (auth.uid() = user_id);
create policy "progress update own" on progress for
update using (auth.uid() = user_id);
-- Gamification: badges and XP
create table if not exists badges (
    id bigserial primary key,
    code text unique not null,
    name text not null,
    description text,
    icon text
);
create table if not exists user_badges (
    user_id uuid not null references profiles(id) on delete cascade,
    badge_id bigint not null references badges(id) on delete cascade,
    awarded_at timestamptz default now(),
    primary key (user_id, badge_id)
);
create table if not exists xp_events (
    id bigserial primary key,
    user_id uuid not null references profiles(id) on delete cascade,
    title_id bigint references titles(id) on delete
    set null,
        event_type text check (event_type in ('watch', 'review', 'quiz')) not null,
        xp_delta int not null,
        created_at timestamptz default now(),
        metadata_json jsonb
);
alter table badges enable row level security;
create policy "badges public read" on badges for
select using (true);
alter table user_badges enable row level security;
create policy "user_badges read own" on user_badges for
select using (auth.uid() = user_id);
create policy "user_badges write own" on user_badges for
insert with check (auth.uid() = user_id);
alter table xp_events enable row level security;
create policy "xp_events read own" on xp_events for
select using (auth.uid() = user_id);
create policy "xp_events write own" on xp_events for
insert with check (auth.uid() = user_id);
-- Social: friends
create table if not exists friends (
    user_id uuid not null references profiles(id) on delete cascade,
    friend_id uuid not null references profiles(id) on delete cascade,
    status text check (status in ('pending', 'accepted')) not null default 'pending',
    created_at timestamptz default now(),
    primary key (user_id, friend_id)
);
alter table friends enable row level security;
create policy "friends read own" on friends for
select using (auth.uid() = user_id);
create policy "friends write own" on friends for
insert with check (auth.uid() = user_id);
create policy "friends update own" on friends for
update using (auth.uid() = user_id);
-- Seed a basic badge
insert into badges (code, name, description, icon)
values (
        'first_watch',
        'First Watch',
        'Je eerste titel gemarkeerd als bekeken',
        '🎬'
    ) on conflict (code) do nothing;