-- Lorely — Multi-Franchise Watch Tracker
-- Complete schema with multi-franchise, canon/retcon, spoilers, tickets, gamification

-- ============================================================
-- FRANCHISES
-- ============================================================

create table if not exists franchises (
    id bigint generated by default as identity primary key,
    code text unique not null,
    name text not null,
    slug text unique not null,
    description text,
    color_primary text,
    color_accent text,
    sort_order int default 0
);

alter table franchises enable row level security;
create policy "franchises public read" on franchises for select using (true);

-- ============================================================
-- TITLES
-- ============================================================

create table if not exists titles (
    id bigint generated by default as identity primary key,
    franchise_id bigint not null references franchises(id) on delete cascade,
    tmdb_id int,
    type text check (type in ('movie', 'series', 'special', 'short')) not null,
    title text not null,
    slug text unique not null,
    release_date date,
    release_status text check (release_status in ('released', 'upcoming', 'announced')) not null default 'released',
    chronology_index numeric,
    story_year text,
    story_order numeric,
    phase text,
    saga text,
    poster_url text,
    backdrop_url text,
    overview text,
    runtime_minutes int,
    streaming_url text,
    streaming_platform text,
    trailer_url text,
    -- Canon system
    canon_level text check (canon_level in ('core', 'extended', 'adjacent', 'standalone')) not null default 'core',
    mcu_relevance_score int check (mcu_relevance_score between 1 and 10) default 5,
    retcon_notes text,
    retconned_by bigint[],
    retcon_date date
);

create index idx_titles_franchise on titles(franchise_id);
create index idx_titles_chronology on titles(franchise_id, chronology_index);
create index idx_titles_story_order on titles(franchise_id, story_order);
create index idx_titles_release_status on titles(release_status);
create index idx_titles_canon_level on titles(canon_level);

alter table titles enable row level security;
create policy "titles public read" on titles for select using (true);

-- ============================================================
-- TITLE VIDEOS (trailers, clips, behind the scenes)
-- ============================================================

create table if not exists title_videos (
    id bigserial primary key,
    title_id bigint not null references titles(id) on delete cascade,
    youtube_key text not null,
    name text not null,
    video_type text check (video_type in ('trailer', 'teaser', 'clip', 'behind_the_scenes', 'featurette', 'bloopers')) not null,
    official boolean not null default false,
    sort_order int default 0,
    unique (title_id, youtube_key)
);

create index idx_title_videos_title on title_videos(title_id);
create index idx_title_videos_type on title_videos(title_id, video_type);

alter table title_videos enable row level security;
create policy "title_videos public read" on title_videos for select using (true);

-- ============================================================
-- RETCONS
-- ============================================================

create table if not exists retcons (
    id bigserial primary key,
    source_title_id bigint not null references titles(id) on delete cascade,
    affected_title_id bigint not null references titles(id) on delete cascade,
    description text not null,
    retcon_type text check (retcon_type in ('canon_change', 'timeline_shift', 'character_change')) not null,
    created_at timestamptz default now()
);

create index idx_retcons_source on retcons(source_title_id);
create index idx_retcons_affected on retcons(affected_title_id);

alter table retcons enable row level security;
create policy "retcons public read" on retcons for select using (true);

-- ============================================================
-- PROFILES
-- ============================================================

create table if not exists profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    username text unique,
    avatar_url text,
    favorite_hero text,
    xp_total int not null default 0,
    level_int int not null default 1,
    streak_current int not null default 0,
    streak_last_date date,
    onboarding_completed boolean not null default false,
    spoiler_mode text check (spoiler_mode in ('smart', 'reveal_all')) not null default 'smart',
    country_code text,
    city text,
    created_at timestamptz default now()
);

alter table profiles enable row level security;

-- Authenticated users can read any profile (needed for friends/leaderboard)
-- Client queries should only select public columns (username, avatar_url, xp_total, level_int)
create policy "profiles read authenticated" on profiles for select using (auth.role() = 'authenticated');
create policy "profiles insert own" on profiles for insert with check (auth.uid() = id);
create policy "profiles update own" on profiles for update using (auth.uid() = id);
-- No delete: profiles are tied to auth.users cascade

-- ============================================================
-- PROGRESS
-- ============================================================

create table if not exists progress (
    user_id uuid not null references profiles(id) on delete cascade,
    title_id bigint not null references titles(id) on delete cascade,
    status text check (status in ('queued', 'watching', 'watched', 'skipped')) not null default 'queued',
    watched_at timestamptz,
    primary key (user_id, title_id)
);

create index idx_progress_user on progress(user_id);
create index idx_progress_status on progress(user_id, status);

alter table progress enable row level security;
create policy "progress read own" on progress for select using (auth.uid() = user_id);
create policy "progress insert own" on progress for insert with check (auth.uid() = user_id);
create policy "progress update own" on progress for update using (auth.uid() = user_id);
create policy "progress delete own" on progress for delete using (auth.uid() = user_id);

-- ============================================================
-- GAMIFICATION: BADGES & XP
-- ============================================================

create table if not exists badges (
    id bigserial primary key,
    code text unique not null,
    name text not null,
    description text,
    icon text,
    franchise_id bigint references franchises(id) on delete set null
);

alter table badges enable row level security;
create policy "badges public read" on badges for select using (true);

create table if not exists user_badges (
    user_id uuid not null references profiles(id) on delete cascade,
    badge_id bigint not null references badges(id) on delete cascade,
    awarded_at timestamptz default now(),
    primary key (user_id, badge_id)
);

create index idx_user_badges_user on user_badges(user_id);

alter table user_badges enable row level security;
create policy "user_badges read own" on user_badges for select using (auth.uid() = user_id);
create policy "user_badges insert own" on user_badges for insert with check (auth.uid() = user_id);

create table if not exists xp_events (
    id bigserial primary key,
    user_id uuid not null references profiles(id) on delete cascade,
    title_id bigint references titles(id) on delete set null,
    event_type text check (event_type in ('watch', 'review', 'quiz', 'badge', 'streak')) not null,
    xp_delta int not null,
    created_at timestamptz default now(),
    metadata_json jsonb
);

create index idx_xp_events_user on xp_events(user_id);
create index idx_xp_events_created on xp_events(user_id, created_at desc);

alter table xp_events enable row level security;
create policy "xp_events read own" on xp_events for select using (auth.uid() = user_id);
create policy "xp_events insert own" on xp_events for insert with check (auth.uid() = user_id);

-- ============================================================
-- CONTEXT SUMMARIES ("Previously On...")
-- ============================================================

create table if not exists context_summaries (
    id bigserial primary key,
    title_id bigint not null references titles(id) on delete cascade,
    prerequisite_title_ids jsonb,
    summary_text text not null,
    key_characters jsonb,
    key_events jsonb,
    spoiler_level text check (spoiler_level in ('safe', 'mild', 'heavy')) not null default 'safe'
);

create index idx_context_summaries_title on context_summaries(title_id);

alter table context_summaries enable row level security;
create policy "context_summaries public read" on context_summaries for select using (true);

-- ============================================================
-- QUIZ
-- ============================================================

create table if not exists quiz_questions (
    id bigserial primary key,
    franchise_id bigint not null references franchises(id) on delete cascade,
    title_id bigint references titles(id) on delete set null,
    question text not null,
    options jsonb not null,
    correct_index int not null,
    difficulty text check (difficulty in ('easy', 'medium', 'hard')) not null default 'medium'
);

create index idx_quiz_questions_franchise on quiz_questions(franchise_id);
create index idx_quiz_questions_title on quiz_questions(title_id);

alter table quiz_questions enable row level security;
create policy "quiz_questions public read" on quiz_questions for select using (true);

create table if not exists quiz_scores (
    id bigserial primary key,
    user_id uuid not null references profiles(id) on delete cascade,
    quiz_id text not null,
    score int not null,
    max_score int not null,
    completed_at timestamptz default now()
);

create index idx_quiz_scores_user on quiz_scores(user_id);
create index idx_quiz_scores_completed on quiz_scores(completed_at desc);

alter table quiz_scores enable row level security;
create policy "quiz_scores read own" on quiz_scores for select using (auth.uid() = user_id);
create policy "quiz_scores insert own" on quiz_scores for insert with check (auth.uid() = user_id);

-- ============================================================
-- SOCIAL: FRIENDS
-- ============================================================

create table if not exists friends (
    user_id uuid not null references profiles(id) on delete cascade,
    friend_id uuid not null references profiles(id) on delete cascade,
    status text check (status in ('pending', 'accepted')) not null default 'pending',
    created_at timestamptz default now(),
    primary key (user_id, friend_id)
);

create index idx_friends_user on friends(user_id);
create index idx_friends_friend on friends(friend_id);

alter table friends enable row level security;
create policy "friends read own" on friends for select using (auth.uid() = user_id or auth.uid() = friend_id);
create policy "friends insert own" on friends for insert with check (auth.uid() = user_id);
-- Only the friend_id (recipient) can accept/reject a request
create policy "friends update recipient" on friends for update using (auth.uid() = friend_id);
create policy "friends delete own" on friends for delete using (auth.uid() = user_id or auth.uid() = friend_id);

-- ============================================================
-- TICKET PROVIDERS
-- ============================================================

create table if not exists ticket_providers (
    id bigserial primary key,
    code text unique not null,
    name text not null,
    logo_url text,
    base_url text,
    country_codes text[] not null
);

alter table ticket_providers enable row level security;
create policy "ticket_providers public read" on ticket_providers for select using (true);

create table if not exists title_tickets (
    id bigserial primary key,
    title_id bigint not null references titles(id) on delete cascade,
    provider_id bigint not null references ticket_providers(id) on delete cascade,
    ticket_url text not null,
    available_from date,
    available_until date
);

create index idx_title_tickets_title on title_tickets(title_id);
create index idx_title_tickets_provider on title_tickets(provider_id);

alter table title_tickets enable row level security;
create policy "title_tickets public read" on title_tickets for select using (true);

-- ============================================================
-- NOTIFICATIONS
-- ============================================================

create table if not exists notifications (
    id bigserial primary key,
    user_id uuid not null references profiles(id) on delete cascade,
    type text check (type in ('new_release', 'ticket_available', 'badge', 'level_up', 'friend', 'quiz', 'streak')) not null,
    title text not null,
    message text,
    data jsonb,
    read boolean not null default false,
    created_at timestamptz default now()
);

create index idx_notifications_user on notifications(user_id);
create index idx_notifications_unread on notifications(user_id, read) where read = false;

alter table notifications enable row level security;
create policy "notifications read own" on notifications for select using (auth.uid() = user_id);
create policy "notifications update own" on notifications for update using (auth.uid() = user_id);

-- ============================================================
-- UPCOMING RELEASES
-- ============================================================

create table if not exists upcoming_releases (
    id bigserial primary key,
    franchise_id bigint not null references franchises(id) on delete cascade,
    title_id bigint not null references titles(id) on delete cascade,
    release_date date not null,
    announced_at timestamptz default now()
);

create index idx_upcoming_releases_franchise on upcoming_releases(franchise_id);
create index idx_upcoming_releases_date on upcoming_releases(release_date);

alter table upcoming_releases enable row level security;
create policy "upcoming_releases public read" on upcoming_releases for select using (true);

-- ============================================================
-- FUNCTIONS
-- ============================================================

-- Recalculate XP for a user (callable by the user themselves or server)
create or replace function fn_recalc_xp(uid uuid)
returns void as $$
declare
    total int;
    new_level int;
begin
    -- Only allow recalc for self or service role
    if auth.uid() is not null and auth.uid() != uid then
        raise exception 'Not authorized';
    end if;
    select coalesce(sum(xp_delta), 0) into total from xp_events where user_id = uid;
    new_level = greatest(1, (total / 500) + 1);
    update profiles set xp_total = total, level_int = new_level where id = uid;
end;
$$ language plpgsql security definer;

-- Server-side function to create notifications (service role only)
create or replace function fn_create_notification(
    p_user_id uuid,
    p_type text,
    p_title text,
    p_message text default null,
    p_data jsonb default null
)
returns bigint as $$
declare
    new_id bigint;
begin
    insert into notifications (user_id, type, title, message, data)
    values (p_user_id, p_type, p_title, p_message, p_data)
    returning id into new_id;
    return new_id;
end;
$$ language plpgsql security definer;

-- ============================================================
-- SEED: MCU Franchise
-- ============================================================

insert into franchises (code, name, slug, description, color_primary, color_accent, sort_order)
values ('mcu', 'Marvel Cinematic Universe', 'mcu', 'Het Marvel Cinematic Universe — van Iron Man tot Secret Wars', '#E53E3E', '#D69E2E', 1)
on conflict (code) do nothing;

-- ============================================================
-- SEED: Badges
-- ============================================================

insert into badges (code, name, description, icon) values
    ('first_watch', 'First Watch', 'Je eerste titel gemarkeerd als bekeken', '🎬'),
    ('phase_1_complete', 'Phase 1 Complete', 'Alle Phase 1 titels bekeken', '🛡️'),
    ('binge_master', 'Binge Master', '5 titels bekeken in 7 dagen', '🔥'),
    ('streak_7', 'Week Warrior', '7 dagen op rij gekeken', '⚡'),
    ('half_way', 'Halfway There', '50% van je gekozen mode voltooid', '🌗'),
    ('completionist', 'Completionist', 'Alle titels in je mode bekeken', '🏆'),
    ('lore_master', 'Lore Master', 'Alle context-samenvattingen gelezen', '📚')
on conflict (code) do nothing;

-- ============================================================
-- SEED: Ticket Providers
-- ============================================================

insert into ticket_providers (code, name, base_url, country_codes) values
    ('pathe', 'Pathé', 'https://www.pathe.nl', '{NL}'),
    ('vue', 'Vue', 'https://www.vuecinemas.nl', '{NL}'),
    ('kinepolis', 'Kinepolis', 'https://kinepolis.nl', '{NL,BE}'),
    ('ugc', 'UGC', 'https://www.ugc.be', '{BE,FR}'),
    ('amc', 'AMC', 'https://www.amctheatres.com', '{US}'),
    ('fandango', 'Fandango', 'https://www.fandango.com', '{US}'),
    ('cinemark', 'Cinemark', 'https://www.cinemark.com', '{US}'),
    ('odeon', 'Odeon', 'https://www.odeon.co.uk', '{GB,IE}'),
    ('cineworld', 'Cineworld', 'https://www.cineworld.co.uk', '{GB,IE}'),
    ('vue_uk', 'Vue UK', 'https://www.myvue.com', '{GB,IE}'),
    ('cinemaxx', 'CinemaxX', 'https://www.cinemaxx.de', '{DE}'),
    ('uci', 'UCI', 'https://www.uci-kinowelt.de', '{DE}')
on conflict (code) do nothing;

-- ============================================================
-- MULTIVERSE: LOCATIONS
-- ============================================================

create table if not exists locations (
    id bigserial primary key,
    code text unique not null,
    name text not null,
    type text check (type in ('planet', 'realm', 'dimension', 'construct', 'region')) not null,
    universe_code text,
    description text,
    color text,
    position_x float default 0,
    position_y float default 0,
    position_z float default 0,
    radius float default 1.0,
    parent_code text
);

create index idx_locations_type on locations(type);
create index idx_locations_universe on locations(universe_code);

alter table locations enable row level security;
create policy "locations public read" on locations for select using (true);

-- ============================================================
-- MULTIVERSE: TITLE ↔ LOCATION
-- ============================================================

create table if not exists title_locations (
    title_id bigint not null references titles(id) on delete cascade,
    location_code text not null references locations(code) on delete cascade,
    is_primary boolean not null default false,
    primary key (title_id, location_code)
);

create index idx_title_locations_title on title_locations(title_id);
create index idx_title_locations_location on title_locations(location_code);

alter table title_locations enable row level security;
create policy "title_locations public read" on title_locations for select using (true);

-- ============================================================
-- MULTIVERSE: UNIVERSES
-- ============================================================

create table if not exists universes (
    id bigserial primary key,
    code text unique not null,
    name text not null,
    designation text,
    description text,
    color text,
    is_sacred boolean not null default false,
    branch_from_code text
);

create index idx_universes_sacred on universes(is_sacred);

alter table universes enable row level security;
create policy "universes public read" on universes for select using (true);

-- ============================================================
-- MULTIVERSE: TIMELINE BRANCHES
-- ============================================================

create table if not exists timeline_branches (
    id bigserial primary key,
    event_name text not null,
    source_title_id bigint references titles(id) on delete set null,
    chronology_point numeric,
    branch_universe_code text,
    description text,
    is_nexus_event boolean not null default false,
    is_pruned boolean not null default false,
    color text
);

create index idx_timeline_branches_source on timeline_branches(source_title_id);
create index idx_timeline_branches_universe on timeline_branches(branch_universe_code);

alter table timeline_branches enable row level security;
create policy "timeline_branches public read" on timeline_branches for select using (true);

-- ============================================================
-- APP CONFIG (themes, icons, feature flags)
-- ============================================================

create table if not exists app_config (
    key text primary key,
    value jsonb not null,
    description text,
    updated_at timestamptz default now()
);

alter table app_config enable row level security;
create policy "app_config public read" on app_config for select using (true);

-- Seed default config
insert into app_config (key, value, description) values
    ('theme', '{"primary": "#E53E3E", "accent": "#D69E2E", "background": "#0A0A0F", "surface": "#1A1A2E", "text": "#FFFFFF"}', 'App-breed kleurenthema'),
    ('badge_icons', '{"first_watch": "🎬", "phase_1_complete": "🛡️", "binge_master": "🔥", "streak_7": "⚡", "half_way": "🌗", "completionist": "🏆", "lore_master": "📚"}', 'Beschikbare badge-iconen'),
    ('canon_levels', '{"core": {"label": "Core MCU", "color": "#E53E3E"}, "extended": {"label": "Extended", "color": "#D69E2E"}, "adjacent": {"label": "Adjacent", "color": "#805AD5"}, "standalone": {"label": "Standalone", "color": "#718096"}}', 'Canon level configuratie'),
    ('experience_modes', '{"simple": {"label": "Simple", "description": "Alleen de kern-films"}, "in_depth": {"label": "In Depth", "description": "Films + series"}, "extreme": {"label": "Extreme", "description": "Alles inclusief multiverse"}}', 'Experience mode beschrijvingen'),
    ('features', '{"quizzes_enabled": true, "leaderboard_enabled": true, "friends_enabled": true, "tickets_enabled": true, "notifications_enabled": true}', 'Feature flags')
on conflict (key) do nothing;
